### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by herndlm** [szepeviktor/phpstan-wordpress#99] opened 2022-04-28 15:08 UTC
I noticed that this extension increases both CPU and memory resources quite a bit. Sorry, I did not have time to profile it, but the "problems" seem to be there since 1.0.0 at least already.

I have quite a small plugin that uses the latest phpstan, phpstan-webmozart-assert extension and phpstan-wordpress extension.

Test case running `vendor/bin/phpstan --debug --verbose analyse`
With this extension: ~17s using ~310M memory
Without this extension:~4s using ~110M memory

Could be something really simple that we need to improve here, who knows. I can profile it soon hopefully. I see slowness in one specific file, so I'll need to inspect that one in particular.

**Comment by herndlm** [comment] 2022-04-28 15:11
I thought about that one as well, but assumed it was added very recently (after 1.0.0). I noticed that all versions since 1.0.0 are more or less affected. Previous ones are just a tiny bit faster. Must be something older I assume

**Comment by herndlm** [comment] 2022-04-28 15:35
OK, I tool a beer home with me from the office fridge I'd like to drink. I'll promise I'll only do that if I either fix this or at least know what _exactly_ is causing it. Wish me luck :)

**Comment by szepeviktor** [comment] 2022-04-28 15:35
Try commenting out this line see seconds and megabytes!
https://github.com/szepeviktor/phpstan-wordpress/blob/00fb9ff3b8199408ead0624be7f74f50e05d935a/extension.neon#L83
(there will be 1 zillion errors)

**Comment by herndlm** [comment] 2022-04-28 20:12
yep, you're absolute right. this "stub file" which is used as bootstrap file is a bit over 4M big and the reason for that apparently. It looks also like it got worse with the latest phpstan versions, e.g. if I go back I can see that almost every minor increased resources a bit :/
1.0.0: 10s/225M, 1.6.0: 14s/305M
1.0.0 (without stubs): 2s/70M,1.6.0 (without stubs): 3s/85M

**Comment by herndlm** [comment] 2022-04-28 20:51
fyi @ondrejmirtes, summary: apparently huge stub/bootstrap files make analysis slow and hog memory. splitting them into smaller files seems to be fine or better at least. does it make sense to look into phpstan itself improving handling of such big (~ 4M) stub/bootstrap files?

**Comment by herndlm** [comment] 2022-04-28 21:02
and another thing that seems to be improving the situation extremely is instead of specifying the huge stubs file as bootstrap file, directly specifying a wordpress-checkout via `scanDirectories`. That was really simple and gave me the best results so far. but how can this be done user friendly for people using this extension 🤔

**Comment by ondrejmirtes** [comment] 2022-04-29 05:24
> apparently huge stub/bootstrap files make analysis slow and hog memory

can you try it with bleedingEdge enabled? And can you find the actual reason why is it slower / takes more memory with php-meminfo? 😊

**Comment by herndlm** [comment] 2022-04-29 06:40
> This makes autoloading extended classes [_impossible_](https://www.youtube.com/watch?v=XAYhNHhxN0A).

does it really? I thought that options was specifically there for such cases, e.g. https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies
but if you can get me some example or describe that case further I'm happy to test :)



> can you try it with bleedingEdge enabled? And can you find the actual reason why is it slower / takes more memory with php-meminfo? 😊

ok, got some new numbers. Unfortunately I'm not really seeing a difference with bleedingEdge
```
phpstan 1.6.3

scanDirectories: 6s/144M
bootstrap stub: 16s/311M
bootstrap stub + bleeding edge: 15-16s/311M (maybe just a bit faster, basically the same)

just to rule that out too: directly executing the stub file  via php takes ~0.1s 
```
Sure, I can try to profile it further, but this might be not easy and take a while. Don't expect results immediately, but I'll try to look into it today/tomorrow :)

**Comment by ondrejmirtes** [comment] 2022-04-29 06:46
Can you please publish the project so I can test it myself and see if I can rule out the cause?

**Comment by herndlm** [comment] 2022-04-29 07:09
Not the one I currently test with unfortunately, but it's easy to reproduce by basically just using this extension. I prepared something at https://github.com/herndlm/phpstan-wordpress-stubs-perf-repro

**Comment by om4csaba** [comment] 2022-04-29 08:01
Another aspect is to reduce the size of the `wordpress-stubs.php` file.

 I wonder whether PHPStan needs to know private/protected method signatures. The WordPress Stubs are generated via the [PHP Stubs Generator](https://github.com/php-stubs/generator), which includes all methods from a class, not just the public ones. 

Keeping only the public methods will reduce the file by around 10 per cent. I am happy to help change the PHP Stubs Generator behaviour.

**Comment by szepeviktor** [comment] 2022-04-29 08:33
> > This makes autoloading extended classes [_impossible_](https://www.youtube.com/watch?v=XAYhNHhxN0A).
> 
> does it really? I thought that option was specifically there for such cases, e.g. [phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies](https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies) but if you can get me some example or describe that case further I'm happy to test :)

I do not have records or an actual example. I have also tries `scanFiles:` but it failed. Maybe it was a WP-CLI command that needs to extend `WPCLI_Command`.

Simply I don't remember.

**Comment by ondrejmirtes** [comment] 2022-04-29 09:16
This is the profile with the extension included: https://blackfire.io/profiles/8e044619-2f50-474f-87a9-dc26b5ba230c/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=in_array&callname=main()&constraintDoc=

The slowest thing is PHPDoc parsing. Because everything is in a single file, PHPStan has to go through all PHPDocs present there. Why splitting into smaller files helps - not all of them have to be searched for a requested class/function.

I think the problem can be solved by making FileTypeMapper a bit more lazy (https://github.com/phpstan/phpstan-src/blob/1.7.x/src/Type/FileTypeMapper.php). When you request a PHPDoc, it's already lazy, but for two reasons PHPDocs are parsed beforehand:

* Type aliases resolving https://github.com/phpstan/phpstan-src/blob/f8be122188aa6721cec9872bd61676ee150a5311/src/Type/FileTypeMapper.php#L534-L556
* TemplateTypeMap resolving https://github.com/phpstan/phpstan-src/blob/f8be122188aa6721cec9872bd61676ee150a5311/src/Type/FileTypeMapper.php#L300-L321

Because both of those are part of NameScope objects where the creation is not lazy.

I'm not saying it's going to be easy :)

**Comment by szepeviktor** [comment] 2022-04-29 09:19
> I'm not saying it's going to be easy :)

Thank you for your work in advance!

**Closed by szepeviktor** 2022-04-29 09:19 UTC

**Comment by herndlm** [comment] 2022-04-29 09:29
And another workaround is still, even without any changes of this extension, to specify a WordPress directory via `scanDirectories`, e.g. https://github.com/johnpbloch/wordpress-core via vendor if that package is installed as dev dep (which also helps phpstorm).

**Comment by ondrejmirtes** [comment] 2022-04-29 09:31
FYI `scanDirectories` can work only with bleedingEdge enabled - if you extend/implement some of those classes.

**Comment by herndlm** [comment] 2022-11-11 09:23
reported at phpstan as https://github.com/phpstan/phpstan/issues/8349 so that we don't forget
